import libtcodpy

LIMIT_FPS = 10

SCREEN_WIDTH = 80
SCREEN_HEIGHT = 45

MAP_WIDTH = 80
MAP_HEIGHT = 40

PANEL_HEIGHT = 7
BAR_WIDTH = 20

MSG_X = BAR_WIDTH + 2
MSG_WIDTH = SCREEN_WIDTH - BAR_WIDTH - 2
MSG_HEIGHT = PANEL_HEIGHT - 1

FOV_ALGORITHM = libtcodpy.FOV_PERMISSIVE_4
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 10

INVENTORY_WIDTH = 50

HEALING_POTION_AMOUNT = 40

LIGHTNING_DAMAGE = 40
LIGHTNING_RANGE = 5

FIREBALL_DAMAGE = 12
FIREBALL_RADIUS = 3

COLOR_ERROR_MESSAGE = libtcodpy.red
COLOR_MAGIC_MESSAGE = libtcodpy.light_blue
COLOR_DAMAGE_MESSAGE = libtcodpy.orange
COLOR_INFO_MESSAGE = libtcodpy.light_cyan

TILE_WALL = 256
TILE_FLOOR = 257
TILE_PLAYER = 258
TILE_ORC = 259
TILE_TROLL = 260
TILE_SCROLL = 261
TILE_HEALING_POTION = 262
TILE_SWORD = 263
TILE_SHIELD = 264
TILE_STAIRS_DOWN = 265
TILE_DAGGER = 266
